import http from 'k6/http';
import { check, sleep } from 'k6';

// Configurable via environment variables
const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const VUS = Number(__ENV.VUS) || 5;
const DURATION = __ENV.DURATION || '30s';

export const options = {
  vus: VUS,
  duration: DURATION,
  thresholds: {
    http_req_failed: ['rate<0.01'],        // Errors < 1%
    http_req_duration: ['p(95)<500'],      // 95% of requests < 500ms
    checks: ['rate>0.99'],                 // At least 99% of checks must pass
  },
};

export default function () {
  // Randomly choose a service for each iteration
  const services = ['slack', 'email'];
  const service = services[Math.floor(Math.random() * services.length)];

  // Generate dynamic payload based on the service
  let payloadData;
  if (service === 'slack') {
    payloadData = {
      text: `K6 Test Message: Hello from VU ${__VU} iter ${__ITER}`,
      channel: '#k6-tests', // Ensure this channel exists
    };
  } else if (service === 'email') {
    payloadData = {
      to: `testuser+vu${__VU}_iter${__ITER}@example.com`,
      subject: `K6 Load Test Email VU ${__VU} Iter ${__ITER}`,
      body: 'This is a test email generated by k6 load test.',
    };
  }

  const url = `${BASE_URL}/api/push/${service}`;
  const params = {
    headers: {
      'Content-Type': 'application/json',
    },
  };

  const res = http.post(url, JSON.stringify(payloadData), params);

  check(res, {
    [`${service} - status is 202`]: (r) => r.status === 202,
    [`${service} - body is OK`]: (r) => r.body && r.body.trim() === 'OK',
  });

  // Simulate realistic user wait time (1–4 seconds)
  sleep(Math.random() * 3 + 1);
}
