import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';

// Configuration
const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const VUS = __ENV.VUS || 5;
const DURATION = __ENV.DURATION || '30s';

// Payloads for different services
const payloads = new SharedArray('notification_payloads', function () {
  return [
    {
      service: 'slack',
      data: {
        text: `K6 Test Message: Hello from VU ${__VU} iter ${__ITER}`,
        channel: '#k6-tests', // Make sure this channel exists or is a valid target
      },
    },
    {
      service: 'email',
      data: {
        to: `testuser+vu${__VU}_iter${__ITER}@example.com`,
        subject: `K6 Load Test Email VU ${__VU} Iter ${__ITER}`,
        body: 'This is a test email generated by k6 load test.',
      },
    },
  ];
});

export const options = {
  vus: VUS,
  duration: DURATION,
  thresholds: {
    http_req_failed: ['rate<0.01'], // http errors should be less than 1%
    http_req_duration: ['p(95)<500'], // 95% of requests should be below 500ms
    checks: ['rate>0.99'], // 99% of checks should pass
  },
};

export default function () {
  // Select a random payload/service
  const payloadConfig = payloads[Math.floor(Math.random() * payloads.length)];
  const service = payloadConfig.service;
  const payload = JSON.stringify(payloadConfig.data);

  const url = `${BASE_URL}/api/push/${service}`;
  const params = {
    headers: {
      'Content-Type': 'application/json',
    },
  };

  const res = http.post(url, payload, params);

  check(res, {
    [`${service} - status is 202`]: (r) => r.status === 202,
    [`${service} - response body is OK`]: (r) => r.body === 'OK',
  });

  // Add a short sleep to simulate user think time or pacing
  sleep(Math.random() * 3 + 1); // Sleep for 1-4 seconds
}

// Optional: Setup and Teardown functions if needed
// export function setup() {
//   console.log('k6 setup: Initializing test...');
//   // You could pre-fetch data or prepare the environment here
// }

// export function teardown(data) {
//   console.log('k6 teardown: Test finished.');
//   // You could clean up resources or post-process results here
// }
